### ISSUE TITLE
AttributeError when using writePsrfits2FromHDF5.py

### ISSUE THREAD

**Issue by ealderet** [lwa-project/pulsar#15]
When converting HDF5 files to PSRFITS using writePsrfits2FromHDF5.py, I receive an error on lines 51 and 62, stating "AttributeError: 'str' object has no attribute 'decode'." If I remove those lines, I can convert files with no issue.

**Comment by jaycedowell** [comment]
I've been able to reproduce this error in CI and it should be fixed as of [09879d2](https://github.com/lwa-project/pulsar/commit/09879d23c48b132256d875d89b8b33f6335e328e).
