### ISSUE TITLE
update for new lsl release

### ISSUE THREAD

**Issue by pratiksan** [lwa-project/pulsar#3]
some old lsl imports are not working, needs to be modified with lsl_upshot.py

**Comment by jaycedowell** [comment]
What, specifically, needs to be updated?

**Comment by pratiksan** [comment]
running the following raises the error below, /usr/local/extensions/Pulsar/writePsrfits2DMulti.py file1 file2

Traceback (most recent call last):
  File "/usr/local/extensions/Pulsar/writePsrfits2DMulti.py", line 35, in <module>
    from lsl.misc.dedispersion import getCoherentSampleSize
ImportError: cannot import name getCoherentSampleSize

In the new version its replaced by, from lsl.misc.dedispersion import get_coherent_sample_size(what I found)

Also, doing python lsl_upshot.py writePsrfits2DMulti.py raises a bunch of possible substitutions (pasted below).

pulsar@lwaucf2:/mnt/toaster/pulsar/B0447-12/59008$ python lsl_upshot.py writePsrfits2DMulti.py 
=== Loaded 298 substitutions ===
writePsrfits2DMulti.py 3c7edba4a95d4558161eafdee4fedfe4 49fc205de77655b671bdf96b71b040cc
86c86
<             except errors.eofError:
---
>             except errors.EOFError:
150,151c150,151
<         srate = idf.getInfo('sampleRate')
<         beampols = idf.getInfo('beampols')
---
>         srate = idf.get_info('sample_rate')
>         beampols = idf.get_info('beampols')
153c153
<         nFramesFile = idf.getInfo('nFrames')
---
>         nFramesFile = idf.get_info('nFrames')
163c163
<         startTimes.append( idf.getInfo('tStartSamples') )
---
>         startTimes.append( idf.get_info('tStartSamples') )
249,250c249,250
<         srate = idf.getInfo('sampleRate')
<         beampols = idf.getInfo('beampols')
---
>         srate = idf.get_info('sample_rate')
>         beampols = idf.get_info('beampols')
252c252
<         nFramesFile = idf.getInfo('nFrames')
---
>         nFramesFile = idf.get_info('nFrames')
264c264
<         tStart = idf.getInfo('tStart') + sampleOffset*spSkip/fS + tickOffset/fS
---
>         tStart = idf.get_info('tStart') + sampleOffset*spSkip/fS + tickOffset/fS
274,276c274,276
<         centralFreq1 = idf.getInfo('freq1')
<         centralFreq2 = idf.getInfo('freq2')
<         beam = idf.getInfo('beam')
---
>         central_freq1 = idf.get_info('freq1')
>         central_freq2 = idf.get_info('freq2')
>         beam = idf.get_info('beam')
280,281c280,281
<         spectraFreq1 = numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) ) + centralFreq1
<         spectraFreq2 = numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) ) + centralFreq2
---
>         spectraFreq1 = numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) ) + central_freq1
>         spectraFreq2 = numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) ) + central_freq2
287c287
<         print "Tunings: %.1f Hz, %.1f Hz" % (centralFreq1, centralFreq2)
---
>         print "Tunings: %.1f Hz, %.1f Hz" % (central_freq1, central_freq2)
295c295
<         print "Samples Needed: %i, %i to %i, %i" % (getCoherentSampleSize(centralFreq1-srate/2, 1.0*srate/LFFT, DM), getCoherentSampleSize(centralFreq2-srate/2, 1.0*srate/LFFT, DM), getCoherentSampleSize(centralFreq1+srate/2, 1.0*srate/LFFT, DM), getCoherentSampleSize(centralFreq2+srate/2, 1.0*srate/LFFT, DM))
---
>         print "Samples Needed: %i, %i to %i, %i" % (getCoherentSampleSize(central_freq1-srate/2, 1.0*srate/LFFT, DM), getCoherentSampleSize(central_freq2-srate/2, 1.0*srate/LFFT, DM), getCoherentSampleSize(central_freq1+srate/2, 1.0*srate/LFFT, DM), getCoherentSampleSize(central_freq2+srate/2, 1.0*srate/LFFT, DM))
298c298
<         if getCoherentSampleSize(centralFreq1-srate/2, 1.0*srate/LFFT, DM) > nsblk:
---
>         if getCoherentSampleSize(central_freq1-srate/2, 1.0*srate/LFFT, DM) > nsblk:
300c300
<         elif getCoherentSampleSize(centralFreq2-srate/2, 1.0*srate/LFFT, DM) > nsblk:
---
>         elif getCoherentSampleSize(central_freq2-srate/2, 1.0*srate/LFFT, DM) > nsblk:
305c305
<         beginDate = ephem.Date(astro.unix_to_utcjd(idf.getInfo('tStart') + nsblk*LFFT/srate) - astro.DJD_OFFSET)
---
>         beginDate = ephem.Date(astro.unix_to_utcjd(idf.get_info('tStart') + nsblk*LFFT/srate) - astro.DJD_OFFSET)
307c307
<         mjd = astro.jd_to_mjd(astro.unix_to_utcjd(idf.getInfo('tStart') + nsblk*LFFT/srate))
---
>         mjd = astro.jd_to_mjd(astro.unix_to_utcjd(idf.get_info('tStart') + nsblk*LFFT/srate))
321c321
<                 pfo.hdr.fctr=centralFreq1/1e6
---
>                 pfo.hdr.fctr=central_freq1/1e6
323c323
<                 pfo.hdr.fctr=centralFreq2/1e6
---
>                 pfo.hdr.fctr=central_freq2/1e6
389,390c389,390
<         freq1 = centralFreq1 + numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) )
<         freq2 = centralFreq2 + numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) )
---
>         freq1 = central_freq1 + numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) )
>         freq2 = central_freq2 + numpy.fft.fftshift( numpy.fft.fftfreq(LFFT, d=1.0/srate) )
394c394
<             skLimits = kurtosis.getLimits(4.0, 1.0*nsblk)
---
>             skLimits = kurtosis.get_limits(4.0, 1.0*nsblk)

**Comment by jaycedowell** [comment]
Wait, `writePsrfits2DMulti.py` looks to have been updated in the repo.  Maybe the version checked out on the cluster is out of date?

**Comment by pratiksan** [comment]
its on node 2

**Comment by jaycedowell** [comment]
It looks like nodes 2 and 4 didn't update `/usr/local/extensions/Pulsar` after PR #2 was merged.  They should be updated now.

**Comment by pratiksan** [comment]
it's working now
